# Generated by Django 3.0.3 on 2020-02-18 07:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('BookInstance', '0002_bookinstance_borrower'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='bookinstance',
            options={'ordering': ['due_back'], 'permissions': (('can_mark_returned', 'Set book as returned'),)},
        ),
    ]
